apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wzqs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0014-tenant/tkrw-pr712-0075-0014-app/devfile-sample-wzqs@sha256:bb659cdb035691ba9d4ecd00d02a8a12005e4e421f7f0d56d917d5ab0b52c006
        name: my-nodejs
        resources: {}
status: {}
